### ISSUE TITLE
Triangle mixin needs completed

### ISSUE THREAD

**Issue by DJTB** [styled-components/polished#160] opened 2017-05-01 19:22 UTC
The docstring for Triangle currently ends up in the built docs under Types > PointingDirection

I went for a quick PR but ran into flow annotation issues due to lack of familiarity with it.

Seems all that's needed is to add `"triangle`" under Mixins in `.documentation.js` and to correct the docstring placement from above `PointingDirection` to above `triangle` in `src/mixins/triangle.js` (and whatever flow wants to be happy ^^).

Moreover, triangle might need to be switched from const arrow => to plain function declaration to match the main export style in the other src files.

**Comment by DJTB** [comment] 2017-05-01 19:32
Oh, I just realised it's not exported in the main package either (attempted to use es6 import).
Not sure if that's an oversight or intentional!

**Comment by bhough** [comment] 2017-05-01 21:55
Thanks @DJTB. It's an oversight, we will take a look at getting that corrected this week.

**Comment by bhough** [comment] 2017-05-01 22:38
@nikgraf @mxstbr looks like this needs a bit of re-working to match our other APIs, documentation is incorrect, and types aren't working exactly right. Will spend some time working on this, this week. Not a bug per se, as it is not usable, but should get it added.

**Comment by bhough** [comment] 2017-05-10 22:40
Closed by #162

**Closed by bhough** 2017-05-10 22:40 UTC
Labels: bug
