### ISSUE TITLE
Strange error with eslint

### ISSUE THREAD

**Issue by EnoahNetzach** [styled-components/polished#134] opened 2017-03-30 14:48 UTC
I just installed **polished**, and ❤️  it (just like **styled-components**)!

There is just one little bug (?) that bothers me..
I use **eslint** for linting, and it keeps saying me that I have 2 errors for each `import polished from 'polished'`:
```
/polished-test/src/Component.js
  2:32  error  Unable to resolve path to module 'polished'  import/no-unresolved
  2:32  error  Missing file extension for "polished"        import/extensions
```

My guess is that in the npm name there is an invisible character..

Here's how to reproduce it:
```bash
git clone https://github.com/EnoahNetzach/polished-test
cd polished-test
yarn
yarn eslint
```

**Comment by mxstbr** [comment] 2017-03-30 15:09
> My guess is that in the npm name there is an invisible character..

Hah that would be super smart, but no it's literally just `"polished"`. I have no idea what's going on here! 🤷‍♂️

**Comment by mxstbr** [comment] 2017-03-30 15:59
Marking this as an unconfirmed bug because I suspect the bug lies with `eslint-plugin-import` but I don't know for sure.

**Comment by EnoahNetzach** [comment] 2017-03-30 16:18
Modifying the **eslint** resolver, forcing it to `console.log` the directory it looks in for the *package.json* (basically [here](https://github.com/substack/node-resolve/blob/master/lib/sync.js#L85)), I get spooky results:

```
 ‌/polished-test/node_modules/polished/package.json
^ there is a hidden char here
```

**Comment by EnoahNetzach** [comment] 2017-03-30 16:25
Opened here: https://github.com/benmosher/eslint-plugin-import/issues/782

**Comment by EnoahNetzach** [comment] 2017-03-31 12:36
@mxstbr I found the elephant in the room 😛

**Comment by EnoahNetzach** [comment] 2017-03-31 12:38
As a footnote, copying output from WebStorm's console *can* append a zwnj char at the beginning, and that was what I was seeing.

**Closed** 2017-03-31 16:00 UTC
Labels: help wanted, unconfirmed bug

**Comment by domwashburn** [comment] 2017-06-22 16:56
I know this is closed, but the comment the ESLint [issue 782](https://github.com/benmosher/eslint-plugin-import/issues/782) was entirely unhelpful and simple says... 

> It was a trivial error in the *polished* package.json, nothing to see here.

will this be fixed?
